name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      CUDA_VISIBLE_DEVICES: ""  # Disable CUDA
      NO_CUDA: "1"  # Disable CUDA in PyTorch
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    
    - name: Train model
      run: |
        python train.py
    
    - name: Run tests
      run: |
        pytest tests/
    
    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/